project:
  type: website
  output-dir: docs

website:
  title: "การแก้ปัญหาทางคณิตศาสตร์อย่างฉลาดรู้ 2"
  navbar:
    search: true
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
  reader-mode: true
  back-to-top-navigation: true
  margin-footer: หากพบปัญหาในการใช้งานเว็บไซต์ กรุณาติดต่ออาจารย์ประจำวิชา

format:
  html:
    theme:
      light: cosmo
      dark:  darkly
    css: styles.css
    toc: true
    page-layout: full
    grid: 
      margin-width: 300px
    smooth-scroll: true



