---
#title: "การแก้ปัญหาทางคณิตศาสตร์อย่างฉลาดรู้ 2"
---

<style>
            body {
              font-family: 'Sarabun', sans-serif;
              font-size: 20px;
            }

            h1 {
              font-family: 'Sarabun', sans-serif;
            }
          </style>


# ยินดีต้อนรับ

เว็บไซต์ทบทวนบทเรียนสำหรับนักเรียนชั้นมัธยมศึกษาปีที่ 2 โรงเรียนสาธิต มศว ประสานมิตร (ฝ่ายมัธยม)จัดทำขึ้นเพื่อช่วยให้นักเรียนได้ทบทวนและทำความเข้าใจเนื้อหาสำคัญในสองหัวข้อหลัก ได้แก่

-   กราฟและความสัมพันธ์

-   รูปเรขาคณิตสองมิติและสามมิติ

เนื้อหาแต่ละบทถูกออกแบบให้เข้าใจง่าย พร้อมตัวอย่างและกิจกรรมแบบ **Scrolltelling** ที่ช่วยให้การเรียนรู้สนุกและเห็นภาพมากขึ้น เหมาะสำหรับการเตรียมความพร้อมก่อนเข้าสู่รายวิชา “การแก้ปัญหาทางคณิตศาสตร์อย่างฉลาดรู้ 2” ที่โรงเรียนจัดขึ้น

เลือกหัวข้อที่ต้องการทบทวนจากลิงก์ด้านล่าง เพื่อเริ่มต้นเรียนรู้และเตรียมความพร้อมสำหรับการเรียนคณิตศาสตร์อย่างมั่นใจ!

# ทบทวนบทเรียน

| หัวข้อ | บทเรียน |
|:----:|:----:|
| กราฟและความสัมพันธ์ ครั้งที่ 1 | [📖](graph_relation.qmd)  |
| กราฟและความสัมพันธ์ ครั้งที่ 2 | [📖](graph_relation2.qmd)  |
| รูปเรขาคณิตสองมิติและสามมิติ | [📖](2d_3d_fig.qmd) |

[**ตรวจสอบผลการส่งงานทบทวนบทเรียน**](result.qmd)
